source=~/.config/mango/conf.d/00-monitors.conf

source=~/.config/mango/conf.d/10-input.conf

source=~/.config/mango/conf.d/20-autostart.conf

source=~/.config/mango/conf.d/30-binds-apps.conf
source=~/.config/mango/conf.d/40-binds-layout.conf

source=~/.config/mango/conf.d/50-appearance.conf 

source=~/.config/mango/conf.d/60-rules.conf
source=~/.config/mango/conf.d/90-misc.conf
