[main]
term=foot
font=MxPlus IBM VGA 8x16 MidTilde:size=12, Symbols Nerd Font Mono:size=12
font-bold=MxPlus IBM VGA 8x16 MidTilde:size=12, Symbols Nerd Font Mono:size=12
font-italic=MxPlus IBM VGA 8x16 MidTilde:size=12, Symbols Nerd Font Mono:size=12
font-bold-italic=MxPlus IBM VGA 8x16 MidTilde:size=12, Symbols Nerd Font Mono:size=12
bold-text-in-bright=palette-based
pad=5x5

[cursor]
style=beam
blink=yes
beam-thickness=1.5

[colors]
alpha=1
background=0c0c0c
foreground=e6e6e6

selection-foreground=ffffff
selection-background=2f3549

urls=88c0d0

# black 
regular0=17160f
bright0=4a4634

# red 
regular1=7b3428
bright1=c05a3e

# green
regular2=687244
bright2=a0aa6b

# yellow
regular3=9b7632
bright3=d0aa56

# blue 
regular4=58675f
bright4=8aa09a

# magenta
regular5=74515a
bright5=b27a86

# cyan
regular6=6f7f69
bright6=a3b89b

# white 
regular7=c8bd98
bright7=f3ead0

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+Shift+f
font-reset=Control+0
