# keyboard rules

repeat_rate=25
repeat_delay=300
numlockon=0

# switching layout
xkb_rules_layout=us,ru
xkb_rules_options=grp:lalt_lshift_toggle

# mouse rules

mouse_natural_scrolling=0
accel_profile=0


