# audio
exec-once=pipewire &
exec-once=pipewire-pulse &
exec-once=wireplumber &

# portals
exec-once=~/.local/bin/start-portals.sh
exec-once=xsettingsd

# foot server
exec-once=foot --server

# wallpaper & bar
exec-once=awww-daemon
exec-once=yambar

# notifications
exec-once=dunst

# clipboard history
exec-once=wl-paste --watch cliphist store
