# apps
bind=SUPER,Return,spawn,footclient
bind=SUPER,escape,spawn,fuzzel
bind=SUPER,w,spawn,librewolf
bind=SUPER,e,spawn,thunar

# wm
bind=SUPER,r,reload_config
bind=SUPER,p,quit
bind=SUPER,q,killclient,

# screenshot / launchers / menus
bind=NONE,Print,spawn,~/.local/bin/screenshot.sh monitor
bind=CTRL,Print,spawn,~/.local/bin/screenshot.sh full
bind=SUPER+SHIFT,s,spawn,~/.local/bin/screenshot.sh area
bind=SUPER+SHIFT,d,spawn,~/.local/bin/screenshot.sh area-swappy

bind=SUPER,v,spawn,~/.local/bin/clipboard
bind=SUPER,x,spawn,~/.local/bin/wallpaper-pick
bind=SUPER,slash,spawn,~/.local/bin/emoji.sh
