# apps
bind=SUPER,Return,spawn,footclient
bind=SUPER,escape,spawn,rofi -show drun
bind=SUPER,w,spawn,librewolf

# wm
bind=SUPER,r,reload_config
bind=SUPER,p,quit
bind=SUPER,q,killclient,

# screenshot / launchers / menus
bind=CTRL+ALT,Delete,spawn,~/.local/bin/powermenu
bind=NONE,Print,spawn,~/.local/bin/screenshot.sh monitor
bind=CTRL,Print,spawn,~/.local/bin/screenshot.sh full
bind=SUPER+SHIFT,s,spawn,~/.local/bin/screenshot.sh area
bind=SUPER+SHIFT,d,spawn,~/.local/bin/screenshot.sh area-swappy

bind=SUPER,v,spawn,~/.local/bin/clipboard
bind=SUPER,x,spawn,~/.local/bin/wallpaper-pick
bind=CTRL+SUPER,x,spawn,~/.local/bin/wallpaper-url-add
bind=SUPER,slash,spawn,~/.local/bin/emoji.sh
