# layouts / window state
bind=SUPER,n,spawn,~/.local/bin/layout.sh
bind=SUPER,c,centerwin
bind=SUPER,d,toggleoverview,
bind=SUPER+ALT,space,togglefloating,
bind=SUPER,f,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# mouse binds
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
drag_tile_to_tile=1
drag_tile_small=0

# swap tags
bind=SUPER+CTRL,Left,viewtoleft
bind=SUPER+CTRL,Right,viewtoright
bind=SUPER+CTRL+SHIFT,Left,tagtoleft
bind=SUPER+CTRL+SHIFT,Right,tagtoright

# move client to tag
bind=Alt,1,tag,1,0
bind=Alt,2,tag,2,0
bind=Alt,3,tag,3,0
bind=Alt,4,tag,4,0
bind=Alt,5,tag,5,0
bind=Alt,6,tag,6,0
bind=Alt,7,tag,7,0
bind=Alt,8,tag,8,0
bind=Alt,9,tag,9,0

# view tag
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# focus direction
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# focus monitors
bind=SUPER+Alt,Left,focusmon,left
bind=SUPER+Alt,Right,focusmon,right

# swap monitors & window
bind=CTRL+SUPER+ALT,Right,tagmon,right
bind=CTRL+SUPER+ALT,Left,tagmon,left
