# Screenshot fix
layerrule=noanim:1,noblur:1,layer_name:selection

# Floating media viewers
windowrule=isfloating:1,appid:mpv
windowrule=isfloating:1,appid:imv

# Thunar transparency
windowrule=focused_opacity:0.80,unfocused_opacity:0.80,appid:^(thunar|Thunar)$
