# Floating pidors
windowrule=isfloating:1,appid:mpv
windowrule=isfloating:1,appid:imv
windowrule=isfloating:1,appid:paradox-launcher-v2
windowrule=isfloating:1,appid:librewolf,title:Bitwarden Password Manager

# screenshots: wayfreeze overlay
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:wayfreeze

# screenshots: slurp selection + Steam toast
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:selection

