canvas_anchor_animate = 1

# Canvas navigation
mousebind = SUPER, BTN_MIDDLE, canvas_drag_pan
bind = SUPER, SPACE, canvas_centerview
bind = SUPER, i, canvas_fill_viewport
bind = SUPER, o, toggleminimap
bind = SUPER, p, canvas_overview_toggle

# Zoom (via axisbind for smooth scrolling)
axisbind = SUPER, UP, canvas_zoom_resize, 1.4
axisbind = SUPER, DOWN, canvas_zoom_resize, 0.6

# Tiling
canvas_tiling = 5
canvas_tiling_gap = 5
canvas_pan_on_kill = 1
