bar:
  monitor: DP-1
  location: top
  layer: top
  height: 20
  background: 060606d9
  foreground: d0d0d0ff
  font: "DejaVu Sans:pixelsize=12,monospace:pixelsize=12"
  spacing: 4

  left:
    - script:
        path: ~/.config/yambar/scripts/workspaces.sh
        content:
          - map:
              default: {empty: {}}
              conditions:
                "show1 && active1":
                  string: {text: "1", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 1"}
                show1:
                  string: {text: "1", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 1"}
          - map:
              default: {empty: {}}
              conditions:
                "show2 && active2":
                  string: {text: "2", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 2"}
                show2:
                  string: {text: "2", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 2"}
          - map:
              default: {empty: {}}
              conditions:
                "show3 && active3":
                  string: {text: "3", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 3"}
                show3:
                  string: {text: "3", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 3"}
          - map:
              default: {empty: {}}
              conditions:
                "show4 && active4":
                  string: {text: "4", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 4"}
                show4:
                  string: {text: "4", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 4"}
          - map:
              default: {empty: {}}
              conditions:
                "show5 && active5":
                  string: {text: "5", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 5"}
                show5:
                  string: {text: "5", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 5"}
          - map:
              default: {empty: {}}
              conditions:
                "show6 && active6":
                  string: {text: "6", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 6"}
                show6:
                  string: {text: "6", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 6"}
          - map:
              default: {empty: {}}
              conditions:
                "show7 && active7":
                  string: {text: "7", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 7"}
                show7:
                  string: {text: "7", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 7"}
          - map:
              default: {empty: {}}
              conditions:
                "show8 && active8":
                  string: {text: "8", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 8"}
                show8:
                  string: {text: "8", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 8"}
          - map:
              default: {empty: {}}
              conditions:
                "show9 && active9":
                  string: {text: "9", margin: 8, foreground: ffffffff, on-click: "mmsg -o DP-1 -s -t 9"}
                show9:
                  string: {text: "9", margin: 8, foreground: "555555ff", on-click: "mmsg -o DP-1 -s -t 9"}

  center:
    - clock:
        time-format: "%H:%M"
        content:
          string: {text: "{time}", foreground: ffffffff}

  right:
    - script:
        path: ~/.config/yambar/scripts/kblayout.sh
        poll-interval: 1000
        content:
          string: {text: "{layout}", margin: 3, foreground: "888888ff"}
    - pulse:
        content:
          map:
            conditions:
              sink_muted:
                string: {text: "mute", margin: 3, foreground: "888888ff", on-click: pavucontrol}
              ~sink_muted:
                string: {text: "{sink_percent}", margin: 3, foreground: "888888ff", on-click: pavucontrol}
